### ISSUE TITLE
Дележка задач

### ISSUE THREAD

**Issue by sergey-lapin** [spb-frontend/p2p-confs#1]
- [ ] найти и добавить слак бота на node, который будет понимать команду echo в приватных сообщениях (возвращать юзеру то, что он написал) @Akurganow https://github.com/spb-frontend/p2p-confs/issues/2
- [x] определится, что за бд мы будем использовать - mongo самый простой вариант(всякие security issues просто не наш случай)
- [ ] сделать тестовые бд с записями, которые имеют пересечение и не имеют, также сделать команду **tryGetIntersectionData(recordId, cb?)**, которая будет возвращать **(null, errorMsg)** в **cb**, если пересечений нет и объект **intersectionData - {dateFrom, dateTo, participantsIdList}**, если есть.
- [ ] **intersectionData** трансформировать в сообщение бота для слака, желательно сделать отдельным модулем для всех подобных трансформаций типа **slackAdapter** - забить туда прочие возможные "фразы" бота
- [ ] найти модуль, который будет распознавать речь (желательно русскую). Сделать функцию **tryParseMeetCmd(userMsg)**, которая будет кидать exception, если проблемы какие при парсе. Если все хорошо возвращает объект **meetUserData - {fromMoment, toMoment}** @lapanoid https://github.com/spb-frontend/p2p-confs/issues/3

**Comment by lapanoid** [comment]
Решили юзать монгу, тк это самое простое. Если эта штука взлетит, тогда и будем про варианты понадежнее и проч.
