### ISSUE TITLE
Распознавать узкий набор текстовых команд

### ISSUE THREAD

**Issue by sergey-lapin** [spb-frontend/p2p-confs#3]
найти модуль, который будет распознавать речь (желательно русскую). Сделать функцию **tryParseMeetCmd(userMsg)**, которая будет кидать exception, если проблемы какие при парсе. Если все хорошо возвращает объект **meetUserData - {fromMoment, toMoment}**

**Comment by Termina1** [comment]
https://github.com/TalAter/annyang

**Comment by lapanoid** [comment]
Я не правильно назвал, мы голос на самом деле не собирались делать. Нам нужно пока всего несколько команд текстовых. Не уверен, что стоит вообще ввязываться в nlp.

**Comment by Termina1** [comment]
@lapanoid ну тогда лучше сформулировать конкретнее )

**Comment by lapanoid** [comment]
примеры команд:
/meet в воскресенье с 18 до 21
или 
/meet среда вечером в 7

hour1:=(int)0<x<24
hour2:=(int)1<x<12
hours:=(hour1|hour2)
timespan1:=<c <hour1>( до <hour1>)?>
timespan2:=((днем|вечером) в <hour2>)
timespans:=(timespan1|timespan2)
dayOfWeek1:=(в|во)<день недели в винительном падеже>
dayOfWeek2:=<день недели в именительном падеже>
dayOfWeeks:=(dayOfWeek1|dayOfWeek2)
/meet (dayOfWeeks)(timespans)(hours)
